version: '3.9'

services:
  web:
    container_name: tracker_backend
    build: .
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - tracker_app
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tracker_app

networks:
  tracker_app:
    driver: bridge

volumes:
  db_data:
    driver: local